spring:
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/serverdb

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
